### ISSUE TITLE
Detection Artefacts - Sysmon Config

### ISSUE THREAD

**Issue by Neo23x0** [RiccardoAncarani/LiquidSnake#1]
Hi Riccardo, 

first - I really like the detection artefacts folder. I haven't seen this very often and its highly appreciated. 

I would have a suggestion : could you please use [this](https://github.com/OTRF/Blacksmith/blob/master/resources/configs/sysmon/sysmon.xml) Sysmon config instead of the one that you've used. Many public ones have only limited rules and I think in the use case like yours it would be better to see what a fully activated Sysmon would be able to see. 
Fore example: this one should then generate events for Named Pipe creations. 

People could then adjust their Sysmon configs accordingly. 

Great work, 

Florian

**Comment by RiccardoAncarani** [comment]
Hi Florian,

No problem at all, I just uploaded the new evtx [with this commit](https://github.com/RiccardoAncarani/LiquidSnake/commit/d2175346393d2199efe99b362301ea86ef3ce7c6). There might be some noise as I was inspecting the processes with ProcessHacker as well, but all the data should be in there.

EDIT: Feel free to open additional issues if you need more data. Also, if you come up with some yara/sigma I'd be happy to include them in the project main page.

Thanks,
Riccardo

**Comment by Neo23x0** [comment]
I've created several rules and adjusted our sysmon config.

Sysmon config adjustments: 
https://github.com/Neo23x0/sysmon-config/pull/15/files?file-filters%5B%5D=.xml

New Sigma rules and refactoring of old ones: 
https://github.com/SigmaHQ/sigma/pull/1969/files

The YARA rules that I wrote are private and haven't been shared except with our customers.
